/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StagesPhaseSlugRouteImport } from './routes/stages.$phaseSlug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StagesPhaseSlugRoute = StagesPhaseSlugRouteImport.update({
  id: '/stages/$phaseSlug',
  path: '/stages/$phaseSlug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/stages/$phaseSlug': typeof StagesPhaseSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/stages/$phaseSlug': typeof StagesPhaseSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/stages/$phaseSlug': typeof StagesPhaseSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/stages/$phaseSlug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/stages/$phaseSlug'
  id: '__root__' | '/' | '/stages/$phaseSlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  StagesPhaseSlugRoute: typeof StagesPhaseSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stages/$phaseSlug': {
      id: '/stages/$phaseSlug'
      path: '/stages/$phaseSlug'
      fullPath: '/stages/$phaseSlug'
      preLoaderRoute: typeof StagesPhaseSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StagesPhaseSlugRoute: StagesPhaseSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
